
#
# This LookML file was generated by AtScale on 2025-05-15T13:09:27.693344219Z
#
# AtScale version: 2025.3.0
# Catalog: atScaleTest_main

connection: "atScaleTest"
label: "atScaleTest_main"


include: "/views/atScaleTest_main/devScale.view.lkml"


explore: devScale {
  label: "devScale"
}

